In [9]:
# importing the necessary packages 
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns 
import requests
from PIL import Image
from io import BytesIO

In [2]:
# going to read in the data 
images = pd.read_csv("https://raw.githubusercontent.com/randa-ama/DS6050-Final-Project/refs/heads/main/data/images.csv")
styles = pd.read_csv("https://raw.githubusercontent.com/randa-ama/DS6050-Final-Project/refs/heads/main/data/styles_FIXED.csv")

In [3]:
# lets take a peak at the data 
images.head()

    filename                                               link
0  15970.jpg  http://assets.myntassets.com/v1/images/style/p...
1  39386.jpg  http://assets.myntassets.com/v1/images/style/p...
2  59263.jpg  http://assets.myntassets.com/v1/images/style/p...
3  21379.jpg  http://assets.myntassets.com/v1/images/style/p...
4  53759.jpg  http://assets.myntassets.com/v1/images/style/p...

In [4]:
# lets take a peak at the data 
styles.head()

,id,gender,masterCategory,subCategory,articleType,baseColour,season,year,usage,productDisplayName,Unnamed: 10,Unnamed: 11
0,15970,Men,Apparel,Topwear,Shirts,Navy Blue,Fall,2011.0,Casual,Turtle Check Men Navy Blue Shirt,NaN,NaN
1,39386,Men,Apparel,Bottomwear,Jeans,Blue,Summer,2012.0,Casual,Peter England Men Party Blue Jeans,NaN,NaN
2,59263,Women,Accessories,Watches,Watches,Silver,Winter,2016.0,Casual,Titan Women Silver Watch,NaN,NaN
3,21379,Men,Apparel,Bottomwear,Track Pants,Black,Fall,2011.0,Casual,Manchester United Men Solid Black Track Pants,NaN,NaN
4,53759,Men,Apparel,Topwear,Tshirts,Grey,Summer,2012.0,Casual,Puma Men Grey T-shirt,NaN,NaN

In [5]:
# i see there is two unnamed columns at the end of the styles dataset; going to iterate through those two columns to see if there are is any data in those columns or its just a function of the csv
unnamed_cols = ['Unnamed: 10','Unnamed: 11']
for cols in unnamed_cols:
    print(styles[cols].isna().sum())

44425
44444

In [6]:
# going to look at the shape for the images and styles csv
print(images.shape)
print(styles.shape)

(44446, 2)
(44446, 12)

In [7]:
# so the images and the styles csv are the same length so i need to see whats in the unnamed columns 
styles['Unnamed: 10'].value_counts()

Unnamed: 10
 Cufflink and Pocket Square Combo Set    14
 its all about me White T-shirt           1
 Blue and Orange Casual Shoes             1
 Silver and Copper Toned Earrings         1
Laugh                                     1
Do It My Way T-shirt                      1
 I don't use it anyway Black T-shirt      1
 Life                                     1
Name: count, dtype: int64

In [8]:
styles['Unnamed: 11'].value_counts()

Unnamed: 11
Love Flip-flops      1
 Laugh Flip Flops    1
Name: count, dtype: int64

In [14]:
# it appears that the unnamed columns are additional information need to look at the images to determine if its important to keep that information or just drop it 
# going to read in the image data; and look at the image to determine if its necessary information 
# creating a funciton to read in the image data 
def load_image_from_url(url):
    response = requests.get(url, timeout=15) 
    image = Image.open(BytesIO(response.content)).convert("RGB")
    return image
# now that i have the function going to use .apply to apply the custom function to the 'link' column in images 
images['image'] = images['link'].apply(lambda url: load_image_from_url(url))

ConnectionError: HTTPConnectionPool(host='assets.myntassets.com', port=80): Max retries exceeded with url: /v1/images/style/properties/7ff58c3f7c1e8b1b7966cc4600c6c38a_images.jpg (Caused by NameResolutionError("<urllib3.connection.HTTPConnection object at 0x128a64f80>: Failed to resolve 'assets.myntassets.com' ([Errno 8] nodename nor servname provided, or not known)"))